services:
  postgres:
    image: postgres:16-alpine
    container_name: ai_devops_postgres
    restart: always
    environment:
      POSTGRES_USER: srujalsau22
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: ai_devops
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U srujalsau22 -d ai_devops"]
      interval: 2s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_devops_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql+psycopg://srujalsau22:devpassword@postgres:5432/ai_devops
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai_devops_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
